<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackAsTool>true</PackAsTool>
		<PackageId>wieseknows.GitReview</PackageId>
		<ToolCommandName>git-review</ToolCommandName>
		<Version>1.0.0</Version>
		<Authors>wieseknows</Authors>
		<Description>CLI tool to convert git diffs into structured LLM prompts.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Update="Templates\prompt.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="TextCopy" Version="6.2.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
	</ItemGroup>
</Project>
