<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>14</LangVersion>
		<UseWPF>true</UseWPF>
		<VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
		<GeneratePkgDefFile>true</GeneratePkgDefFile>
		<VsixDeployOnDebug>true</VsixDeployOnDebug>
		<IncludeDebugSymbolsInLocalVSIXDeployment>true</IncludeDebugSymbolsInLocalVSIXDeployment>

		<StartAction>Program</StartAction>
		<StartProgram>$(DevEnvDir)devenv.exe</StartProgram>
		<StartArguments>/rootsuffix Exp</StartArguments>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\gitreview-png.png" />
	  <None Remove="Assets\ss-example.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\gitreview-png.png" />
	  <Content Include="Assets\ss-example.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectCapability Include="CreateVsixContainer" />
	</ItemGroup>

	<ItemGroup>
		<VSCTCompile Include="VSCommandTable.vsct">
			<ResourceName>Menus.ctmenu</ResourceName>
		</VSCTCompile>

		<Page Update="ToolWindows\GitReviewToolWindowControl.xaml">
			<Generator>MSBuild:Compile</Generator>
			<SubType>Designer</SubType>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Design" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
		<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\GitReview.Shared\GitReview.Shared.csproj" />
	</ItemGroup>

</Project>